name: "2. Build & Deploy App"

on:
  workflow_dispatch: # Allows manual run from GitHub Actions tab

jobs:
  build-and-push:
    name: Build, Push to ECR, and Refresh ASG
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:${{ github.sha }} .
          docker push $REGISTRY/$REPOSITORY:${{ github.sha }}
      - name: update image tag in state file
        run: |
          terraform init -backend-config="bucket=${{ secrets.BUCKET_NAME }}"
          terraform apply -var="image_tag=${{ github.sha }}" -auto-approve
